# Generated by Django 4.1.3 on 2022-11-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='acortador_url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('acor_url', models.CharField(blank=True, max_length=15, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'acordor_url',
                'verbose_name_plural': 'acortadores_url',
                'ordering': ['-created'],
            },
        ),
    ]
