# Generated by Django 4.1.3 on 2022-11-28 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acortador_url', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acortador_url',
            name='acor_url',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
