# Generated by Django 4.1.4 on 2023-01-06 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acortador_url", "0002_alter_acortador_url_acor_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="acortador_url",
            name="acor_url",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
