# Generated by Django 4.2.2 on 2023-06-17 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acortador_url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('acor_url', models.CharField(max_length=18, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('profiles', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'acordor_url',
                'verbose_name_plural': 'acortadores_url',
                'ordering': ['-created'],
            },
        ),
    ]
