# Generated by Django 4.2.2 on 2023-06-17 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shorcuter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acortador_url',
            name='acor_url',
            field=models.CharField(max_length=18),
        ),
    ]
